### ISSUE TITLE
bug in md_static

### ISSUE THREAD

**Issue by DCM-Uni-Paderborn** [DCM-Uni-Paderborn/RPMD_Mainz#1]
an filename  string in md_static is  empty  preventing the program from executing

**Comment by Ithanil** [comment]
Fixed this bug, but immediately ran into the next Issue: 

At line 46 of file /home/ithanil/Resilio/PostMaster/Code/RPMD_Mainz/src/RDF_obj.f90
Fortran runtime error: Index '4' of dimension 3 of array 'geo.0' outside of expected range (1:1)

Will commit the fix and open another issue.
