### ISSUE TITLE
Used param file missing in test directory.

### ISSUE THREAD

**Issue by Ithanil** [DCM-Uni-Paderborn/RPMD_Mainz#3]
I would like to run the test in tests directory, but the params file used to generate the output is not present.

**Comment by DCM-Uni-Paderborn** [comment]
that output was not supposed to be there :( I added the directory for future use, as in, when someone adds a new feature, say a langevin thermostat, he can also add a test case.
Feel free to remove that stuff from the repository  and close the thread.

**Comment by Ithanil** [comment]
Ok I see. I think it wouldn't be bad to add a little test script already, which executes an input with all stuff enabled and compares against expected output. Maybe I will do it later today or tomorrow.

**Comment by Ithanil** [comment]
Can be closed: https://github.com/DCM-Uni-Paderborn/RPMD_Mainz/commit/b9fc92ae94ffe2076af793c540905482b6cd3f74
